name: Deploy React App to Azure Web App

on:
  push:
    branches:
      - main  # or your deployment branch

env:
  AZURE_WEBAPP_NAME: prosares-dev10         # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './build'      # set this to the path to your web app project, defaults to the repository root      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.14.0'  # Use the version that matches your project

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.AZURE_WEBAPP_NAME}}           
        publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
        package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
